### ISSUE TITLE
Example config files

### ISSUE THREAD

**Issue by kornpow** [wizardsardine/liana#559]
When I run `lianad`:
```
$ ./liana-1.0-x86_64-linux-gnu/lianad 
Error parsing config: Could not locate the configuration file.
```

I try and figure out what flags may exist here, but that also fails.
```
$ ./liana-1.0-x86_64-linux-gnu/lianad -h
Unknown arguments '["./liana-1.0-x86_64-linux-gnu/lianad", "-h"]'.
Only '--conf <configuration file path>' is supported.

$ ~/Documents/projects/liana$ ./liana-1.0-x86_64-linux-gnu/lianad help
Unknown arguments '["./liana-1.0-x86_64-linux-gnu/lianad", "help"]'.
Only '--conf <configuration file path>' is supported.
```
Please show examples of available config options.

I like how LND has an example available on the top level of the repo:
https://github.com/lightningnetwork/lnd/blob/master/sample-lnd.conf

**Comment by jdlcdl** [comment]
I think I ran into similar problems this morning.   I suspect that the expected way is to start the gui, create your first wallet, connect to a node, and then "start" will actually write your configuration.

My tasks were:
* upgrade my bitcoind to v24.0 or above (I went with v25).
* configure it without rpcuser/rpcpasswd so that it creates a .cookie file... and run this node as the same user as liana... because otherwise I had problems with bitcoind not being able to create wallet files in ~/.liana (perms probs).
* I did away with my cargo/rust installed by apt and installed latest cargo/rustc via rustup.
* I had no problems doing 'cargo build --release' for lianad/liana-cli nor for the gui within the gui folder.

**Comment by pythcoiner** [comment]
you can run lianad headless by this command:

```sh
lianad --conf ~/.liana/signet/daemon.toml
```
where daemon.toml looks like that:
``` toml
daemon = false
data_dir = "/home/user/.liana"
log_level = "INFO"
main_descriptor = "wsh(or_d(pk([842a626e/48'/1'/0'/2']tpubDENBboujRvpkS8SgZsrpqG2BCUBoaAc4c57jHFe1NwKAtfVjDZDUadQKYv4pkAEF2afPv6TtQ2BoYFJAPLbuKpL1usiySERZekGo4JmnWhh/<0;1>/*),and_v(v:pk([40259ab7/48'/1'/0'/2']tpubDFcY6nTiMAWBd5d2bS8JZvjcaLjC6GE6XnPAJAPUkVj5wa5Pyb4gumx1ZWvnXQ8tmorCmpAyai69K9hD2mGQUeNkuXfjztsfqnE5FMk1CCh/<0;1>/*),older(65535))))#rk8yff2s"

[bitcoin_config]
network = "signet"
poll_interval_secs = 30

[bitcoind_config]
addr = "127.0.0.1:38332"
cookie_path = "/home/user/.signet/signet/.cookie"
```
